name: probabl-forecasting
channels:
  - conda-forge
dependencies:
  - notebook >=7.4.3,<8
  - jupyterlab >=4.4.3,<5
  - jupytext >=1.17.2,<2
  - scikit-learn >=1.7.0,<2
  - polars ==1.24.0
  - matplotlib-base >=3.10.3,<4
  - pyarrow >=20.0.0,<21
  - holidays >=0.75,<0.76
  - pip >=25.1.1,<26
  - ipyleaflet >=0.20.0,<0.21
  - pandas >=2.3.0,<3
  - mlforecast >=1.0.2,<2
  - altair >=5.5.0,<6
  - graphviz >=13.1.0,<14
  - pydot >=4.0.1,<5
  - u8darts >=0.36.0,<0.37
  - setuptools <81
  - plotly >=6.2.0,<7
  - skrub ==0.6.0
  - pip:
    - openmeteo-requests >=1.5.0, <2
    - requests-cache >=1.2.1, <2
    - retry-requests >=2.0.0, <3