[project]
name = "Skrub DataOps applied to forecasting timeseries"
version = "0.1.0"
description = "Skrub DataOps applied to forecasting timeseries"
authors = ["Guillaume Lemaitre <guillaume@probabl.ai>",
"Olivier Grisel <olivier@probabl.ai>",
"Riccardo Cappuzzo <riccardo.cappuzzo@inria.fr>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
notebook = ">=7.4.3,<8"
jupyterlab = ">=4.4.3,<5"
jupytext = ">=1.17.2,<2"
scikit-learn = ">=1.7.0,<2"
polars = "==1.24.0" # same as latest compatible emscripten build
matplotlib-base = ">=3.10.3,<4"
pyarrow = ">=20.0.0,<21"
holidays = ">=0.75,<0.76"
pip = ">=25.1.1,<26"
ipyleaflet = ">=0.20.0,<0.21"
pandas = ">=2.3.0,<3"
altair = ">=5.5.0,<6"
graphviz = ">=13.1.0,<14"
pydot = ">=4.0.1,<5"
plotly = ">=6.2.0,<7"
cloudpickle = ">=3.0.0,<3.1"
skrub = "==0.6.1"

[pypi-dependencies]
openmeteo-requests = ">=1.5.0, <2"
requests-cache = ">=1.2.1, <2"
retry-requests = ">=2.0.0, <3"

[feature.dev.dependencies]
ipykernel = "*"

[feature.lint.dependencies]
ruff = "*"
black = "*"

[feature.doc.dependencies]
jupyter-book = "*"
jupyterlite = "*"
jupyterlite-pyodide-kernel = "*"
python-libarchive-c = "*"

[feature.doc.tasks]
execute-file-creating-pickle = { cmd = "python feature_engineering.py", cwd = "content/python_files" }
create-notebooks-dir = { cmd = "mkdir -p ./content/notebooks" }
copy-pickled-pipelines = { cmd = "cp ./content/python_files/*.pkl ./content/notebooks/", depends-on = ["create-notebooks-dir", "execute-file-creating-pickle"] }
copy-tutorial-helpers = { cmd = "cp ./content/python_files/tutorial_helpers.py ./content/notebooks/tutorial_helpers.py", depends-on = ["create-notebooks-dir"] }
copy-parallel-coordinates-plots = { cmd = "cp ./content/python_files/*.json ./content/notebooks/", depends-on = ["create-notebooks-dir"] }
convert-to-notebooks = { cmd = "jupytext --to notebook ./content/python_files/*.py && mv ./content/python_files/*.ipynb ./content/notebooks", depends-on = ["create-notebooks-dir", "copy-tutorial-helpers", "copy-parallel-coordinates-plots"] }
convert-to-executed-notebooks = { cmd = "jupytext --to notebook --execute ./content/python_files/*.py && mv ./content/python_files/*.ipynb ./content/notebooks", depends-on = ["create-notebooks-dir", "copy-pickled-pipelines", "copy-tutorial-helpers", "copy-parallel-coordinates-plots"] }
build-book = { cmd = "jupyter-book build book", depends-on = ["convert-to-notebooks", "copy-tutorial-helpers", "copy-parallel-coordinates-plots"] }
build-jupyterlite = { cmd = "jupyter lite build --contents content --output-dir dist", cwd = "jupyterlite", depends-on = ["convert-to-notebooks"] }
serve-jupyterlite = { cmd = "python -m http.server", cwd = "jupyterlite/dist", depends-on = ["build-jupyterlite"] }
build-slides = { cmd = "quarto render", cwd = "content/slides"}

[environments]
lint = ["lint"]
doc = ["doc"]
dev = ["dev", "doc", "lint"]
